### ISSUE TITLE
Tuning profiles maybe need adjusting for Sat6.8 and later using Postgresql12 (checkpoint_segments deprecated)

### ISSUE THREAD

**Issue by SlyDragons** [RedHatSatellite/satellite-support#74]
Satellite 6.8 replaced the postgresql9 with version 12.

The tuning profiles have postresql configuration "checkpoint_segments" that cause the **satellite-installer** to throw errors in Sat6.8 and later due to the deprecation of checkpoint_segments in 9.4.    I *believe* the comparable option would be some combination of "min_wal_size" and  "max_wal_size", but I'm not sure what would be most appropriate.  

~~~
ERROR:
  checkpoint_segments tuning found in /etc/foreman-installer/custom-hiera.yaml
  This tuning option is no longer valid in PostgreSQL 9.5+
  Please remove this from the following locations and then re-run the installer:
    - /etc/foreman-installer/custom-hiera.yaml
    - /var/opt/rh/rh-postgresql12/lib/pgsql/data/postgresql.conf
The presence of checkpoint_segments in /etc/foreman-installer/custom-hiera.yaml indicates manual tuning.
Manual tuning can override values provided by the --tuning parameter.
Review /etc/foreman-installer/custom-hiera.yaml for values that are already provided by the built in tuning profiles.
Built in tuning profiles also provide a supported upgrade path.
~~~

**Comment by wbclark** [comment]
Hi @SlyDragons thank you for the issue report!

Starting with Satellite 6.7, the tuning profiles are built into the installer and exist at e.g. `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes/large.yaml` and can be specified with `satellite-installer --tuning large`. The configuration in question has already been removed from those built in tuning profiles (see: https://github.com/theforeman/foreman-installer/commit/e077f41baf6323f6f15200e27603eec24bcf37d8#diff-458284b14a18c0e7e6e85bdf64eb0342e462463bc0bb65e8a4f172f0ffe1b6bd ) so using the new built in tuning feature rather than custom-hiera.yml will solve the error you faced.

Meanwhile `custom-hiera.yml` still exists, and has a higher order of precedence than the built in tuning profiles. This design of moving the tuning profiles out of custom hiera achieves separation of the tuning profiles as a base starting point, and additional or override configuration specified by the user.

At this time, the supported Satellite versions are 6.7, 6.8, and 6.9 meaning there is no reason for these legacy tuning profiles to exist in this repository any longer. I'll shortly open a PR here to remove them and make the new design more clear in the documentation.

Thanks again for bringing this to our attention and let us know if you have any further questions about it.

Cheers,

**Comment by wbclark** [comment]
Closing with https://github.com/RedHatSatellite/satellite-support/pull/75

Thanks!
